### ISSUE TITLE
MARKET-216 JPA Persistence Lib Connector - Step 1 JPA Demo

### ISSUE THREAD

**Issue by majeed-hm** [axonivy-market/market#246]
Hi @ivy-rew ,

Can you please review the following JPA Demo:
https://github.com/majeed-hm/jpa-persistence-lib

**Comment by ivy-rew** [comment]
Thanks for contributing @majeed-hm . 
You're repo has been forked and will be reviewed here: 
https://github.com/axonivy-market/persistence-utils/pull/1

**Comment by ivy-rew** [comment]
Let's gain experience with the new review process outlined as tasks @ivy-lmu 

# Review Tasks

## Product Domain

- [ ] product successfully installs into the Axon.ivy Designer
- [ ] product parts are marked as `Connector` or `Demo`
- [ ] the product projects contains documentation to explain the functionality or use-case: 
   e.g. `Process-Notes`, `Input-Parameter` descriptions, Meta-Comments on `variables.yaml` definitions ...
- [ ] the product readme fits into the market landscape @andreasbalsiger
- [ ] all mandatory setup steps to run the Demo are documented in the setup section of the `[myProduct]/product/Readme.md` .

## Technical Solution

### Coherent

- [ ] Common group-id for all artifacts `<groupId>[org.arcme|com.axonivy].[util|connector].[product-name]<groupId>`
- [ ] Common artifact-id prefix: `<artifactId>msgraph[-product|test|demo]</artifactId>`
- [ ] Html-Dalogs depend on suggested 'frame' template
- [ ] Github actions + maven-build runs as outlined in market-product template

### Maintainable

- [ ] Dependent third-party infrastructure (e.g. Database, MavenRepos) is available: public accessible instance or shared as code (e.g. Docker, docker-compose)
- [ ] Tests are implemented that verify, that the product actually runs
- [ ] Additional libraries (e.g. Maven dependencies) are lightweight: not duplicating libaries of the `Axon.ivy Classpath Container`.
- [ ] Depends on standard Axon.ivy features and does not light-heartedly re-introduce forks of existing solutions (e.g. Job-Framework). Our goal is to integrate also third-parties into existing: Enginge-Cockpit-View, Log-Channels, Monitoring features, ...
- [ ] Uses latest ivy-environment: e.g. process-files and used project-build-plugin match the ivyProject version.
- [ ] Product is re-usable without the need to unpack and customize it for standard use-cases: crucial settings can be overriden with well documented `config/variables.yaml`
