### ISSUE TITLE
Onboard [name] to Axon-ivy market

### ISSUE THREAD

**Issue by majeed-hm** [axonivy-market/market#268]
Hi @alexsuter  ,
the link to the Demo image in maket place is always referencing the old repo.
![image](https://user-images.githubusercontent.com/23138636/202669563-cf2f004c-4443-427c-aeec-6d251b450bd2.png)

I am assuming this is wrong in [market](https://github.com/axonivy-market/market/tree/master/market)/[demos](https://github.com/axonivy-market/market/tree/master/market/demos)/[stateful-datatable](https://github.com/axonivy-market/market/tree/master/market/demos/stateful-datatable)/meta.json:
![image](https://user-images.githubusercontent.com/23138636/202669669-1511f2b4-b2a0-4bdb-97f2-2b4af609e652.png)

can you please check it? 

[[link-to-your-product-repo](https://market.axonivy.com/stateful-datatable-demo)]

* * *
⚠️ do not remove this section, but leave it to track the reviewer's work.

# Review Tasks

## Product Domain

- [ ] product successfully installs into the Axon.ivy Designer
- [ ] product parts are marked as `Connector` or `Demo`
- [ ] the product projects contains documentation to explain the functionality or use-case: 
   e.g. `Process-Notes`, `Input-Parameter` descriptions, Meta-Comments on `variables.yaml` definitions ...
- [ ] the product readme fits into the market landscape @andreasbalsiger
- [ ] all mandatory setup steps to run the Demo are documented in the setup section of the `[myProduct]/product/Readme.md` .

### Coherent

- [ ] Common group-id for all artifacts `<groupId>[org.arcme|com.axonivy].[util|connector].[product-name]<groupId>`
- [ ] Common artifact-id prefix: `<artifactId>msgraph[-product|test|demo]</artifactId>`
- [ ] Html-Dalogs depend on suggested 'frame' template
- [ ] Github actions + maven-build runs as outlined in market-product template

### Maintainable

- [ ] Dependent third-party infrastructure (e.g. Database, MavenRepos) is available: public accessible instance or shared as code (e.g. Docker, docker-compose)
- [ ] Tests are implemented that verify, that the product actually runs
- [ ] Additional libraries (e.g. Maven dependencies) are lightweight: not duplicating libaries of the `Axon.ivy Classpath Container`.
- [ ] Depends on standard Axon.ivy features and does not light-heartedly re-introduce forks of existing solutions (e.g. Job-Framework). Our goal is to integrate also third-parties into existing: Enginge-Cockpit-View, Log-Channels, Monitoring features, ...
- [ ] Uses latest ivy-environment: e.g. process-files and used project-build-plugin match the ivyProject version.
- [ ] Product is re-usable without the need to unpack and customize it for standard use-cases: crucial settings can be overriden with well documented `config/variables.yaml`

**Comment by alexsuter** [comment]
This image must be included in the product zip. It isn't, this is because you have named the PNG image with UPPERCASE Ending.

https://github.com/axonivy-market/stateful-datatable/tree/master/stateful-datatable-product

You can fix it, by renaming it from DemoCapture.png to DemoCapture.PNG

Then you will need to release a new version,

**Comment by majeed-hm** [comment]
Thank you Alex. I renamed the extension to png but the CI-Build is not working on the AxonIvy market repo: https://github.com/axonivy-market/stateful-datatable/actions
although it is already working for the original repo: https://github.com/majeed-hm/stateful-datatable-demo/actions
