### ISSUE TITLE
Onboard [db-demos] to Axon-ivy market

### ISSUE THREAD

**Issue by ivy-tgr** [axonivy-market/market#276]
Hi, I've just created a market-product that I'd like to publish into the official axonivy-market. 
Can you fork it and review my cool product?
https://github.com/axonivy-market/db-demos

* * *
⚠️ do not remove this section, but leave it to track the reviewer's work.

# Review Tasks

## Product Domain

- [x] product successfully installs into the Axon Ivy Designer
- [x] product parts are marked as `Connector` or `Demo`
- [x] the product projects contains documentation to explain the functionality or use-case: 
   e.g. `Process-Notes`, `Input-Parameter` descriptions, Meta-Comments on `variables.yaml` definitions ...
- [x] the product readme fits into the market landscape @andreasbalsiger
- [x] all mandatory setup steps to run the Demo are documented in the setup section of the `[myProduct]/product/Readme.md` .

### Coherent

- [x] Common group-id for all artifacts `<groupId>[org.arcme|com.axonivy].[util|connector].[product-name]<groupId>`
- [x] Common artifact-id prefix: `<artifactId>msgraph[-product|test|demo]</artifactId>`
- [x] Html-Dalogs depend on suggested 'frame' template
- [x] Github actions + maven-build runs as outlined in market-product template

### Maintainable

- [x] Dependent third-party infrastructure (e.g. Database, MavenRepos) is available: public accessible instance or shared as code (e.g. Docker, docker-compose)
- [x] Tests are implemented that verify, that the product actually runs
- [x] Additional libraries (e.g. Maven dependencies) are lightweight: not duplicating libaries of the `Axon.ivy Classpath Container`.
- [x] Depends on standard Axon Ivy features and does not light-heartedly re-introduce forks of existing solutions (e.g. Job-Framework). Our goal is to integrate also third-parties into existing: Enginge-Cockpit-View, Log-Channels, Monitoring features, ...
- [x] Uses latest ivy-environment: e.g. process-files and used project-build-plugin match the ivyProject version.
- [x] Product is re-usable without the need to unpack and customize it for standard use-cases: crucial settings can be overriden with well documented `config/variables.yaml`

**Comment by ivy-rew** [comment]
please align the groupdId of all your maven artifacts with the existing demo namespaces (e.g. workflow-demos or connectivity-demos) should serve well as exmpale @ivy-tgr
