### ISSUE TITLE
Cron Job Process Start Connector

### ISSUE THREAD

**Issue by weissreto** [axonivy-market/market#280]
Hi, I'm in need for a connector or product for Cron Job Process Start.

## Customer

Most of our customers out there

## Use Cases

As a developer i want to use the Cron Programm Start Bean without using the portal, but by downloading a Marketplace Item that provides this functionality.

    create a new marketplace connector with name: “Automated Process Start Utils” 

    create an demo project that uses the new connector

    Isolate the CronByGlobalVariableTriggerStartEventBean.java and use it as connector

## Integration

/portal/src/ch/ivy/addon/portalkit/util/CronByGlobalVariableTriggerStartEventBean.java

**Comment by alexsuter** [comment]
one step left for @majeed-hm 

https://github.com/axonivy-market/cronjob/pull/1

**Comment by alexsuter** [comment]
its available
