### ISSUE TITLE
SAP HANA Connector

### ISSUE THREAD

**Issue by weissreto** [axonivy-market/market#282]
Hi, I'm in need for a connector or product for SAP HANA.

## Customer

Implemented for one of our customer projects

## Use Cases

As Developer I want to have a simple SAP HANA Connector to connect the SAP HANA system.

## Integration

A first example is already available: https://bitbucket.org/gsenft/ivy-s4hana-sample

The next steps are
- Transform the example to an Market Place Connector
- Follow the instructions 
- The transformation should be done by Application Support (Helmut) in cooperation with our iConnect Team

* * *
⚠️ do not remove this section, but leave it to track the reviewer's work.

# Review Tasks

## Product Domain

- [x] product successfully installs into the Axon Ivy Designer
- [x] product parts are marked as `Connector` or `Demo`
- [x] the product projects contains documentation to explain the functionality or use-case: 
   e.g. `Process-Notes`, `Input-Parameter` descriptions, Meta-Comments on `variables.yaml` definitions ...
- [x] the product readme fits into the market landscape @andreasbalsiger
- [x] all mandatory setup steps to run the Demo are documented in the setup section of the `[myProduct]/product/Readme.md` .

### Coherent

- [x] Common group-id for all artifacts `<groupId>[org.arcme|com.axonivy].[util|connector].[product-name]<groupId>`
- [x] Common artifact-id prefix: `<artifactId>msgraph[-product|test|demo]</artifactId>`
- [x] Html-Dalogs depend on suggested 'frame' template
- [x] Github actions + maven-build runs as outlined in market-product template

### Maintainable

- [x] Dependent third-party infrastructure (e.g. Database, MavenRepos) is available: public accessible instance or shared as code (e.g. Docker, docker-compose)
- [x] Tests are implemented that verify, that the product actually runs
- [x] Additional libraries (e.g. Maven dependencies) are lightweight: not duplicating libaries of the `Axon.ivy Classpath Container`.
- [x] Depends on standard Axon Ivy features and does not light-heartedly re-introduce forks of existing solutions (e.g. Job-Framework). Our goal is to integrate also third-parties into existing: Enginge-Cockpit-View, Log-Channels, Monitoring features, ...
- [x] Uses latest ivy-environment: e.g. process-files and used project-build-plugin match the ivyProject version.
- [x] Product is re-usable without the need to unpack and customize it for standard use-cases: crucial settings can be overriden with well documented `config/variables.yaml`

**Comment by drag0p** [comment]
I think the test till now was using a real mock server (it was great to test against a real service), but this mock server isnt available anymore, 
As you write a @IvyProcessTest with mock data would be needed, i am not sure how much time I will have to work on this ...
The problem is I have other projects so its hard to find time...

**Comment by phhung-axonivy** [comment]
The connector is live in the first version: https://market.axonivy.com/s4hana-connector
Thanks for all your work @drag0p, @andreasbalsiger, @ivy-sgi.
