### ISSUE TITLE
Onboard Master Detail Demo to Axon-ivy market

### ISSUE THREAD

**Issue by fkalanti** [axonivy-market/market#302]
Hi, I've just created a market-product that I'd like to publish into the official axonivy-market. 
Can you fork it and review my cool product?
https://github.com/fkalanti/master-detail

* * *
⚠️ do not remove this section, but leave it to track the reviewer's work.

# Review Tasks

## Product Domain

- [x] product successfully installs into the Axon Ivy Designer
- [x] product parts are marked as `Connector` or `Demo`
- [x] the product projects contains documentation to explain the functionality or use-case: 
   e.g. `Process-Notes`, `Input-Parameter` descriptions, Meta-Comments on `variables.yaml` definitions ...
- [x] the product readme fits into the market landscape @andreasbalsiger
- [x] all mandatory setup steps to run the Demo are documented in the setup section of the `[myProduct]/product/Readme.md` .

### Coherent

- [x] Common group-id for all artifacts `<groupId>[org.arcme|com.axonivy].[util|connector].[product-name]<groupId>`
- [x] Common artifact-id prefix: `<artifactId>msgraph[-product|test|demo]</artifactId>`
- [x] Html-Dalogs depend on suggested 'frame' template
- [x] Github actions + maven-build runs as outlined in market-product template

### Maintainable

- [x] Dependent third-party infrastructure (e.g. Database, MavenRepos) is available: public accessible instance or shared as code (e.g. Docker, docker-compose)
- [x] Tests are implemented that verify, that the product actually runs
- [x] Additional libraries (e.g. Maven dependencies) are lightweight: not duplicating libaries of the `Axon.ivy Classpath Container`.
- [x] Depends on standard Axon Ivy features and does not light-heartedly re-introduce forks of existing solutions (e.g. Job-Framework). Our goal is to integrate also third-parties into existing: Enginge-Cockpit-View, Log-Channels, Monitoring features, ...
- [x] Uses latest ivy-environment: e.g. process-files and used project-build-plugin match the ivyProject version.
- [x] Product is re-usable without the need to unpack and customize it for standard use-cases: crucial settings can be overriden with well documented `config/variables.yaml`

**Comment by ivy-rew** [comment]
hi @ivy-sgi 

we have a new product onboarding. This would be a good opportunity to teach Octopus how to handle such requests, that new products can actually make it into the market.
It's a quite frequent occurring task and will cost the maintainers of the Market time and spontaneous commitment to serve the contributors.

Do we already have a "Market" confluence space? So that I could document the internal procedure for the review? Would an Octopus developer invest 1-2 h to go through the review with me?

**Comment by ivy-sgi** [comment]
Hi @ivy-rew !
Very fresh confluence space can be found here: https://1ivy.atlassian.net/wiki/spaces/MARP/overview (we also have a jira here: https://1ivy.atlassian.net/jira/software/c/projects/MARP/issues - but still empty).

I appreciate to get insights into the onboarding process - just invite me and @nqhoan-axonivy (keep in mind that there are 5 hours time difference).

**Comment by ivy-rew** [comment]
thanks for contributing @fkalanti , we're just starting the review https://github.com/axonivy-market/master-detail/pull/1

**Comment by andreasbalsiger** [comment]
Hello @fkalanti and @nqhoan-axonivy with @ivy-sgi: I think we had another description text for the read me:

Axon Ivy's Master-detail interface best-practice example is designed to accelerate process automation initiatives by demonstrating the flexible and powerful UI possibilities. This example showcases the following features:

- Three different approaches to implementing the Master-Detail Pattern are demonstrated based on the project's complexity. These approaches involve utilizing different process elements, UI views, and modal dialogs.
- Streamlining UI challenges for both professional developers and low coders, this example provides guidance on efficiently implementing the Master-Detail interface.
- This best-practice example is a valuable resource for resolving [Master-Detail interface](https://en.wikipedia.org/wiki/Master%E2%80%93detail_interface) requirements in any process automation project.

Can you make sure to replace the existing text with this one (as on https://github.com/axonivy-market/master-detail/pull/1)

thx
Best,
Andreas

**Comment by ivy-rew** [comment]
> Hello @fkalanti and @nqhoan-axonivy with @ivy-sgi: I think we had another description text for the read me:
> 
> Axon Ivy's Master-detail interface best-practice example is designed to accelerate process automation initiatives by demonstrating the flexible and powerful UI possibilities. This example showcases the following features:
> 
>     * Three different approaches to implementing the Master-Detail Pattern are demonstrated based on the project's complexity. These approaches involve utilizing different process elements, UI views, and modal dialogs.
> 
>     * Streamlining UI challenges for both professional developers and low coders, this example provides guidance on efficiently implementing the Master-Detail interface.
> 
>     * This best-practice example is a valuable resource for resolving [Master-Detail interface](https://en.wikipedia.org/wiki/Master%E2%80%93detail_interface) requirements in any process automation project.
> 
> 
> Can you make sure to replace the existing text with this one (as on [axonivy-market/master-detail#1](https://github.com/axonivy-market/master-detail/pull/1))
> 
> thx Best, Andreas

- [ ] adapt the description from @andreasbalsiger  onto the readme.md @fkalanti

**Comment by nqhoan-axonivy** [comment]
Thank @fkalanti so much for your contribution!
I would like to inform you that your project is built/deployed to the Axon Ivy Market successfully!
The code can be maintained at https://github.com/axonivy-market/master-detail. In the future, you and everyone can continue to contribute to this git source.
So right now, I would like to close this issue as Done.

**Comment by fkalanti** [comment]
Thank you also @nqhoan-axonivy  and @ivy-rew for your help to publish it and the valueable feedback! We will continue to do great stuff together!
