### ISSUE TITLE
Order of actions in the documentation does not work in real life

### ISSUE THREAD

**Issue by ivy-tru** [axonivy-market/market#365]
Hi @ivy-sgi 

We ran into lot of confusion about these steps.
![image](https://github.com/axonivy-market/market/assets/26996440/4f529f3c-d35a-48ff-bc31-3cec385934c8)

As the release build action only works for a repo in the market GitHub account, we cannot do the release build first and then to the onboarding. We need the onboarding as a precondition for the release build.

![image](https://github.com/axonivy-market/market/assets/26996440/e2297e9a-453e-4152-aa1e-7cbca007e462)

![image](https://github.com/axonivy-market/market/assets/26996440/35ded2e6-b658-4714-86b2-758f52ca3163)

Maybe this should be changed in the documentation. Or maybe the process needs to be fixed to also work in our own repo.

Best regards,
Timo

**Comment by ivy-rew** [comment]
I think there's no easy way to change this behavior. As we rely upon the packaging infrastructure shared within the axonivy-market org. However, the documentation should be adjust to the reality ... repos can life anywhere during development time, which makes is possible to start anywhere without asking guys within the market.org to create repos. For a first release and onboarding however, the repo must life in the axonivy-market org.

**Comment by ivy-sgi** [comment]
Hi @ivy-tru @ivy-rew ! Thanks a lot for your feedback - I have changed the order of "Creating a release" and "publish and celebrate" in the guideline: https://github.com/axonivy-market/market/wiki/c3-Market-Integration

**Comment by ivy-rew** [comment]
> Hi @ivy-tru @ivy-rew ! Thanks a lot for your feedback - I have changed the order of "Creating a release" and "publish and celebrate" in the guideline: https://github.com/axonivy-market/market/wiki/c3-Market-Integration

Cool, Thanks @ivy-sgi
