### ISSUE TITLE
Onboard Advanced Process Analyzer to Axon Ivy market

### ISSUE THREAD

**Issue by ivy-tru** [axonivy-market/market#369]
Hi, 
Team Everest has just created a market-product that I'd like to publish into the official axonivy-market. 
Can you fork it and review my cool product?

https://github.com/axonivy-professional-services/market-process-analyzer/

Here you can find some image proposals from @andreasbalsiger which could be used for the product on public market website: [APA-Images.zip](https://github.com/axonivy-market/market/files/15166669/APA-Images.zip)

* * *
⚠️ do not remove this section, but leave it to track the reviewer's work.

# Review Tasks

## Product Domain

- [x] product successfully installs into the Axon Ivy Designer
- [x] product parts are marked as `Connector` or `Demo`
- [x] the product projects contains documentation to explain the functionality or use-case: 
   e.g. `Process-Notes`, `Input-Parameter` descriptions, Meta-Comments on `variables.yaml` definitions ...

### Coherent

- [x] Common group-id for all artifacts `<groupId>[org.arcme|com.axonivy].[util|connector].[product-name]<groupId>`
- [x] Common artifact-id prefix: `<artifactId>msgraph[-product|test|demo]</artifactId>`
- [x] Html-Dalogs depend on suggested 'frame' template
- [x] Github actions + maven-build runs as outlined in market-product template

### Maintainable

- [x] Dependent third-party infrastructure (e.g. Database, MavenRepos) is available: public accessible instance or shared as code (e.g. Docker, docker-compose)
- [x] Tests are implemented that verify, that the product actually runs
- [x] Additional libraries (e.g. Maven dependencies) are lightweight: not duplicating libaries of the `Axon.ivy Classpath Container`.
- [x] Depends on standard Axon Ivy features and does not light-heartedly re-introduce forks of existing solutions (e.g. Job-Framework). Our goal is to integrate also third-parties into existing: Enginge-Cockpit-View, Log-Channels, Monitoring features, ...
- [x] Uses latest ivy-environment: e.g. process-files and used project-build-plugin match the ivyProject version.
- [x] Product is re-usable without the need to unpack and customize it for standard use-cases: crucial settings can be overriden with well documented `config/variables.yaml`

## Second Pull request: Description

- [x] the product readme fits into the market landscape (Andreas Balsinger)
- [x] all mandatory setup steps to run the Demo are documented in the setup section of the `[myProduct]/product/Readme.md` .

**Comment by ivy-sgi** [comment]
Hi @andreasbalsiger ! If you are happy with the name of this product (Process Analyzer) we could close this ticket.

My 5 cents: This utility is rather an "EndTimeEstimator" (asking chatGPT for variations: FinishPredictor, EstimateEndTime, CompletionForecaster).

Process Analyser is very similiar to "ProcessMining" - which is not a happy comparison.

@ivy-tru @andreasbalsiger What is your opinion?

**Comment by ivy-tru** [comment]
@ivy-sgi My initial name was "Workflow Estimator"

**Comment by ivy-sgi** [comment]
So let's go with Workflow Estimator? @ivy-tru

**Comment by ivy-tru** [comment]
We had a meeting in the early development phase to decide about the name and result was "Advanced Process Analyzer". I'm not a marketing guy, I just see the effort to change names back and forth (documentation, namespaces, artifact names, ...).

In my opinion it's quite late to change the name. I vote for keeping the current name and closing the ticket.

**Comment by ivy-sgi** [comment]
Hi Timo! We (Team Octopus) did that for other connectors already, so time should not be the argument. Just let's find the best name. "Advanced Process Analyzer" is too long as the implementation for the market place homepage currently only allows names with 24 chars or less - Advances Process Analyser has 25 :( 

I am still a fan of "Workflow Estimator" because it best describes what the connector actually does.

**Comment by ivy-tru** [comment]
Hi @ivy-sgi 
Okay, I also like the name. In case we rename, it would be great to rename before the knowledge transfer meeting - which is on Thursday. Because we should use the final name for our presentation. People may be confused, when we rename afterwards.
