### ISSUE TITLE
Onboard cms-editor to Axon-ivy market

### ISSUE THREAD

**Issue by tvtphuc-axonivy** [axonivy-market/market#406]
Hi, I've just created a market-product that I'd like to publish into the official axonivy-market. 
Can you fork it and review my cool product?
[[cms-editor]](https://github.com/linhpd-axonivy/cms-editor)

* * *
⚠️ do not remove this section, but leave it to track the reviewer's work.

# Review Tasks

## Product Domain

- [x] product successfully installs into the Axon Ivy Designer
- [x] product parts are marked as `Connector` or `Demo`
- [x] the product projects contains documentation to explain the functionality or use-case: 
   e.g. `Process-Notes`, `Input-Parameter` descriptions, Meta-Comments on `variables.yaml` definitions ...

### Coherent

- [x] Common group-id for all artifacts `<groupId>[org.arcme|com.axonivy].[util|connector].[product-name]<groupId>`
- [x] Common artifact-id prefix: `<artifactId>msgraph[-product|test|demo]</artifactId>`
- [x] Html-Dalogs depend on suggested 'frame' template
- [x] Github actions + maven-build runs as outlined in market-product template

### Maintainable

- [x] Dependent third-party infrastructure (e.g. Database, MavenRepos) is available: public accessible instance or shared as code (e.g. Docker, docker-compose)
- [x] Tests are implemented that verify, that the product actually runs
- [x] Additional libraries (e.g. Maven dependencies) are lightweight: not duplicating libaries of the `Axon.ivy Classpath Container`.
- [x] Depends on standard Axon Ivy features and does not light-heartedly re-introduce forks of existing solutions (e.g. Job-Framework). Our goal is to integrate also third-parties into existing: Enginge-Cockpit-View, Log-Channels, Monitoring features, ...
- [x] Uses latest ivy-environment: e.g. process-files and used project-build-plugin match the ivyProject version.
- [x] Product is re-usable without the need to unpack and customize it for standard use-cases: crucial settings can be overriden with well documented `config/variables.yaml`

## Second Pull request: Description

- [x] the product readme fits into the market landscape (Sabine Gillner)
- [x] all mandatory setup steps to run the Demo are documented in the setup section of the `[myProduct]/product/Readme.md` .

**Comment by ivy-sgi** [comment]
Hi @tvtphuc-axonivy !
What about the following text for the description-tag:

In AxonIvy, languages for UIs, notifications, or emails are managed within the CMS. We are excited to introduce the new CMS editor that significantly simplifies language editing! The key features are:

- User-friendly editor for adding new languages
- Edit an unlimited number of languages
- Simple styles available
- No HTML tags needed in the translation text

**Comment by ivy-sgi** [comment]
Hi @linhpd-axonivy This is the text we talked about in the daily.

**Comment by linhpd-axonivy** [comment]
Hi @ivy-sgi ,
Please help me review the README, logo, and meta.json for the CMS editor here:
https://github.com/axonivy-market/cms-editor/blob/feature/MARP-577-Handle-feedback-release-CMS-as-utility/README.md
https://github.com/axonivy-market/market/pull/409/files

**Comment by ivy-rew** [comment]
any reasons for not closing this issue yet @linhpd-axonivy ?

**Comment by linhpd-axonivy** [comment]
Thank you for the reminder, @ivy-rew. I will close it now.
