### ISSUE TITLE
Onboard DB-Utils to Axon-ivy market

### ISSUE THREAD

**Issue by peters-axon** [axonivy-market/market#442]
Hi, I've just created a market-product that I'd like to publish into the official axonivy-market. 
Can you fork it and review my cool product?

[[Db-Utils Repo]](https://github.com/peters-axon/db-utils/)

* * *
⚠️ do not remove this section, but leave it to track the reviewer's work.

# Review Tasks

## Product Domain

- [x] product successfully installs into the Axon Ivy Designer
- [x] product parts are marked as `Connector` or `Demo`
- [x] the product projects contains documentation to explain the functionality or use-case: 
   e.g. `Process-Notes`, `Input-Parameter` descriptions, Meta-Comments on `variables.yaml` definitions ...

### Coherent

- [x] Common group-id for all artifacts `<groupId>[org.arcme|com.axonivy].[util|connector].[product-name]<groupId>`
- [x] Common artifact-id prefix: `<artifactId>msgraph[-product|test|demo]</artifactId>`
- [x] Html-Dalogs depend on suggested 'frame' template
- [x] Github actions + maven-build runs as outlined in market-product template

### Maintainable

- [x] Dependent third-party infrastructure (e.g. Database, MavenRepos) is available: public accessible instance or shared as code (e.g. Docker, docker-compose)
- [x] Tests are implemented that verify, that the product actually runs
- [x] Additional libraries (e.g. Maven dependencies) are lightweight: not duplicating libaries of the `Axon.ivy Classpath Container`.
- [x] Depends on standard Axon Ivy features and does not light-heartedly re-introduce forks of existing solutions (e.g. Job-Framework). Our goal is to integrate also third-parties into existing: Enginge-Cockpit-View, Log-Channels, Monitoring features, ...
- [x] Uses latest ivy-environment: e.g. process-files and used project-build-plugin match the ivyProject version.
- [x] Product is re-usable without the need to unpack and customize it for standard use-cases: crucial settings can be overriden with well documented `config/variables.yaml`

## Second Pull request: Description

- [x] the product readme fits into the market landscape
- [ ] all mandatory setup steps to run the Demo are documented in the setup section of the `[myProduct]/product/Readme.md` and a German translation for the description section are provided in `[myProduct]/product/Readme_DE.md` .

**Comment by linhpd-axonivy** [comment]
Hi @peters-axon ,
I have some minor feedback on the PR https://github.com/axonivy-market/db-utils/pull/2. Please take a look at it.

**Comment by linhpd-axonivy** [comment]
Hi @peters-axon ,
I created a new PR for the product icon and meta.json: https://github.com/axonivy-market/market/pull/450. Please help me update the logo and meta.json for the product.

**Comment by ivy-rew** [comment]
Hi @linhpd-axonivy 

It seems like @peters-axon is still not allowed to directly contribute to the new repository.
![db-utils-owners](https://github.com/user-attachments/assets/79a20586-1d60-41f5-82e9-f90fe850d51d)


Therefore he faces strange failures in actions build with release-drafter which can be avoided by working in the same repo.

How do you ensure, that the onboarded product developers are given the correct permissions and being guided to the new repo? It seems to me that this task is not in the issue-template and therefore forgotten at times?

**Comment by linhpd-axonivy** [comment]
Hi @ivy-rew ,
We have already defined the process for granting permissions in our review guidelines. I will grant permission to Peter before releasing the project.

![image](https://github.com/user-attachments/assets/88d80d5d-2d4f-4322-9d6a-0dc05f1f7bd5)

**Comment by ivy-rew** [comment]
> Hi @ivy-rew , We have already defined the process for granting permissions in our review guidelines. I will grant permission to Peter before releasing the project.
> 
> ![image](https://private-user-images.githubusercontent.com/138570547/375327397-88d80d5d-2d4f-4322-9d6a-0dc05f1f7bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTU1MzgsIm5iZiI6MTcyODU1NTIzOCwicGF0aCI6Ii8xMzg1NzA1NDcvMzc1MzI3Mzk3LTg4ZDgwZDVkLTJkNGYtNDMyMi05ZDZhLTBkYzA1ZjFmN2JkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxMDEzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWY5OTA1MzI0OTk0NDJiZDlkNTY4YjA0MTZjOTYzOWFlMzNlYzg3ZGVlZDE3Y2E0MTBjMTVhNzBjMzFkYWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BkuTheD_a14rcTv-pXK035lcJE9HLHxAa3ZI5ilO6Dc)

thanks for sharing @linhpd-axonivy , sorry I forgot about this internal guideline.
so I'll wait patiently :wink:
